Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/CyclomaticComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: hash_rockets

Style/IfUnlessModifier:
  Enabled: false

Style/MethodCallParentheses:
  Enabled: false

Style/MethodLength:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
