#!/usr/bin/env ruby

lib = File.expand_path("../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "expression"

bindings = {}

loop do
  print "calc> "
  input = gets
  input = input.chomp if input # This is here to handle Ctrl+D

  case input
  when "exit", nil
    puts "Bye bye!"
    exit
  # e.g., lines that look like x = 20
  when /^([a-z]+)\s*=\s*(-*\d+)$/
    bindings[$1] = $2.to_i
  else
    begin
      puts Expression.new(input).evaluate(bindings)
    rescue StandardError => err
      puts "Error evaluating RPN expression: #{input.inspect}"
      puts err
    end
  end
end
